# Generated by Django 2.0.7 on 2018-07-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
