# Generated by Django 2.0.7 on 2018-07-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_auto_20180721_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='deal',
            field=models.ManyToManyField(to='life.Deal'),
        ),
    ]
