# Generated by Django 2.0.7 on 2018-07-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_auto_20180722_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='deal',
            new_name='deals',
        ),
    ]
