# Generated by Django 2.0.7 on 2018-07-22 22:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('life', '0010_auto_20180722_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopper',
            new_name='Profile',
        ),
    ]
